# Generated by Django 5.1.5 on 2025-01-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_rename_date_worklog_date_logged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='billed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='billed_status',
            field=models.CharField(choices=[('billed', 'Billed'), ('processed', 'Processed'), ('unbilled', 'Unbilled')], default='unbilled', max_length=20),
        ),
        migrations.AddField(
            model_name='worklog',
            name='processed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
