# Generated by Django 5.1.5 on 2025-01-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0007_alter_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
