# Generated by Django 5.1.5 on 2025-02-01 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0008_alter_invoice_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='estimated_time',
        ),
        migrations.AlterField(
            model_name='function',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='projectrate',
            unique_together={('project', 'developer')},
        ),
    ]
