# Generated by Django 5.1.5 on 2025-02-01 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0010_historicalproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeveloperRate',
        ),
    ]
