# Generated by Django 5.1.4 on 2025-01-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_role_alter_user_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin'), ('developer', 'Developer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='authentication.skill'),
        ),
    ]
